$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
display_name: diabetes-training-yml
inputs:
  data:
    path: ../experimentation/data/
    type: uri_folder
  learning_rate: 0.25
  registered_model_name: diabetes-data-train-job-yml
  train_test_ratio: 0.2
code: ./model/
command: python train.py --training_data ${{inputs.data}}  --reg_rate ${{inputs.learning_rate}} --registered_model_name ${{inputs.registered_model_name}} --train_test_ratio ${{inputs.train_test_ratio}}
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu:36 
compute: azureml:CompCluster01
experiment_name: "azure_job_for_diabetes_training_job_yaml"
description: "Read the daiabetes csv file, train a logistic regression model from it using sklearn."
