name: On Pull req Code checks Automatically challenge-03

on:
  pull_request:

jobs:
  job1:
    name: linting
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"


