name: experiment-train-dev
on:
  [workflow_dispatch, pull_request, workflow_call]
jobs:
  train:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_dev.yml --resource-group smibrahimhossain-rg --workspace-name Myfirstworkspace


