name: Production train prod

on:
  workflow_dispatch:

jobs:
  login_checkout:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
  experiments:
    uses: ./.github/workflows/05-experiment_train.yml
  train:
    needs: [experiments]
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job_prod.yml --resource-group smibrahimhossain-rg --workspace-name Myfirstworkspace


